### PR TITLE
Expand tabs to spaces

### PR DESCRIPTION
**Pull request by rmyorston**
Expand tabs to spaces and add an option to allow the user to
specify the size of a tabstop.

### CODE REVIEW

**Comment by avih** [comment]
Thanks.

In general, I object to converting tabs to spaces, especially by default, the same way that `cat` doesn't do that. Also, if you then copy the output from the terminal then you'll get spaces instead of tabs (in terminals which actually copy tabs as tabs - like xterm).

I don't object to configuring the tab number, because indeed currently it's an assumption, which could be incorrect. However, this is still partial, because terminal tab stops are not necessarily regular.

Isn't this PR a subset of just using `expand [-t<definition>] FILE | shlolcat` ?  where `<definition>` can be a single number, like in this PR, or a list of stops - similar to what the POSIX `tabs` utility accepts, or convert to spaces with default of `-t8` if `-tTABS` is not given.

In general, I prefer to keep shlolcat doing one thing, hopefully well - color the output. Combining the functionality of different standard utilities using pipes is preferred, IMHO, over embedding the functionality of other utilities into shlolcat.

Don't you agree?

**Comment by rmyorston** [comment]
Sure, your reasoning is sound.

While I'm here, in shlolcat it says:
>050/051 are '(',')' stay(rom)

stay(rom)?

**Comment by avih** [comment]
> stay(rom)?

Descriptive, right? :)

It's a shortened version, to fit at the same line, of "ESC(N and ESC)N is rom character select sequence. The value of `e` stays at 1".

See more info and concrete use case where this happens at the commit message - https://github.com/avih/shlolcat/commit/c1b2d51911834b95a98379c06598e9375450a3da

There are more values which can benefit from extending the "1st char after esc" state, e.g. if you do `vim | shlolcat` or some other app which can use complex sequences (well, you probably want `clolcat` for interactive apps, as it doesn't have the output buffering which `shlolcat` has), but rom select was the only one I encountered in practice.

FWIW, `vim|clolcat` amazingly seems to work perfectly.

**Comment by avih** [comment]
Anyway, closing now. Feel free to reopen if you want to add only configurable tab width.

**Pull request closed without merging**
